language: node_js
node_js: 8
branches:
  only:
    - master
addons:
  ssh_known_hosts: 106.12.140.131
install:
  - yarn install
script:
  - yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
before_install:
  - openssl aes-256-cbc -K $encrypted_2a01126f8b17_key -iv $encrypted_2a01126f8b17_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 106.12.140.131\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - scp -o stricthostkeychecking=no -r docs/.vuepress/dist root@106.12.140.131:/root
